### ISSUE TITLE
OGSOD-1.0的旋转框

### ISSUE THREAD

**Issue by lsyss-lsyss** [mmic-lcl/Datasets-and-benchmark-code#19]
您好, 请问下OGSOD-1.0数据集有旋转框吗, 论文里面说有

**Comment by mmic-lcl** [comment]
感谢关注，我们近期将整理好数据更新相关链接。

**Comment by lsyss-lsyss** [comment]
您好, 请问下有的SAR图片是彩色的, 这是什么情况

**Comment by mmic-lcl** [comment]
已补充旋转标签和OSPRC数据集的链接

**Comment by mmic-lcl** [comment]
彩色SAR图像我们再检查下相关数据，后面会更新相关回答或链接。

**Comment by wangchaosar** [comment]
> 您好, 请问下有的SAR图片是彩色的, 这是什么情况

可以具体说一下哪几张图片吗？（给几个图像的编号）

**Comment by lsyss-lsyss** [comment]
您好, SAR数据集train里面的1.png, 看上去是有彩色斑点, 用opencv开发现bgr3个通道像素值不一样, 正常应该是bgr3个通道像素值一样的灰度图

**Comment by mmic-lcl** [comment]
已更新数据链接
