### ISSUE TITLE
LasHeR评测工具

### ISSUE THREAD

**Issue by yesidooo** [mmic-lcl/Datasets-and-benchmark-code#2]
您好，在使用您的matlab代码时，读取属性标注时出现了问题。58行报错：‘‘无法执行赋值，因为左侧的大小为 1-by-1216，右侧的大小为 304-by-4。‘’具体位置如下，请问应该如何修改呢？如有打扰，敬请见谅。
for i = 1:num_seq
name_seq_all{i} = sequences{i};
seq_att = dlmread(fullfile(path_att, [sequences{i} '.txt']));
if i == 1
att_all = zeros(num_seq, numel(seq_att));
end
att_all(i, :) = seq_att; ‘’----------此行报错---------‘’
end

**Comment by yangmengmeng1997** [comment]
你好，这边我没有遇到过这种错误，我也是用的Lasot的包来测试的，我这边属性测试没有问题，如果 你方便的话可以加我QQ：1459834870，可以更加具体的看看你遇到什么问题

**Comment by mmic-lcl** [comment]
已更新LasHeR评测代码
