### ISSUE TITLE
关于HiAl数据集论文详情

### ISSUE THREAD

**Issue by Jasper0420** [mmic-lcl/Datasets-and-benchmark-code#22]
您好！

关注到贵组提供的Multimodal Object Tracking Dataset Based on High Altitude Drones这个数据集，但是没找到相应的论文？请问是在审未公开，还是我没找到的原因呢？如果已经公开，方便提供一下文章链接吗？谢谢！

祝好！

**Comment by mmic-lcl** [comment]
感谢关注，论文如下，请查收。
[Uploading HiAl_基于高空无人机平台的多模态跟踪数据集.pdf…]()

**Comment by FreshmanMa** [comment]
您好，能否提供给Pytracking下HiAI的dataloader 文件？
