### ISSUE TITLE
您好，我对您的文章非常感兴趣，想请问一下您能提供关于Category-Oriented Localization Distillation for SAR Object Detection and a Unified Benchmark这篇文章的代码吗？

### ISSUE THREAD

**Issue by xiaodingzi0** [mmic-lcl/Datasets-and-benchmark-code#26]

**Comment by mmic-lcl** [comment]
感谢关注，这篇文章的代码链接如下：

**Comment by mmic-lcl** [comment]
感谢关注，这篇文章的代码如下链接：https://pan.baidu.com/s/1-K8PTevI2A7P2SVZIyls6Q?pwd=vnxj 
提取码：vnxj

**Comment by xiaodingzi0** [comment]
非常感谢您的分享，祝您及全体课题组科研顺利，生活愉快！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mmic-lcl/Datasets-and-benchmark-code"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月22日(星期二) 下午4:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mmic-lcl/Datasets-and-benchmark-code] 您好，我对您的文章非常感兴趣，想请问一下您能提供关于Category-Oriented Localization Distillation for SAR Object Detection and a Unified Benchmark这篇文章的代码吗？ (Issue #26)





 
感谢关注，这篇文章的代码如下链接：https://pan.baidu.com/s/1-K8PTevI2A7P2SVZIyls6Q?pwd=vnxj
 提取码：vnxj
