### ISSUE TITLE
关于Dense Tiny Object Detection Dataset中的一些问题。

### ISSUE THREAD

**Issue by wap1024** [mmic-lcl/Datasets-and-benchmark-code#28]
您好，对于您Dense Tiny Object Detection: A Scene Context Guided Approach and a Unified Benchmark的工作，拜读之后，我觉得您做得工作很不错，但是我打开您放在paper中的链接，我没有找到SCDNet算法的代码，请问您能否提供下相应的代码，期待您的答复，非常感谢您。

**Comment by mmic-lcl** [comment]
欢迎关注我们的工作，代码会在未来开源，可以先使用我们开源的数据集广泛评测，我们的评测方法借鉴了https://github.com/shaunyuan22/CFINet

**Comment by wap1024** [comment]
好的，谢谢您的回复
