### ISSUE TITLE
Cannot download the dataset

### ISSUE THREAD

**Issue by furkancoskun** [mmic-lcl/Datasets-and-benchmark-code#3]
When I try to download the baidu links, I got the error:

> 啊哦，你所访问的页面不存在了。
可能的原因：
> 1.在地址栏中输入了错误的地址。
> 2.你点击的某个链接已过期。

Translated to English:

> Oops, the page you're visiting no longer exists.
possible reason:
> 1. The wrong address was entered in the address bar.
> 2. A link you clicked on has expired.

It seems like links are expired. Can you, please, update the links? Thank you

**Comment by mmic-lcl** [comment]
I re-verified all the baidu links, and all of them are accessible successfully.  Which link are you unable to access?
