### ISSUE TITLE
论文复现

### ISSUE THREAD

**Issue by ciqian6** [mmic-lcl/Datasets-and-benchmark-code#30]
您好，非常感谢您分享的Category-Oriented Localization Distillation for SAR Object Detection and a Unified Benchmark这篇文章源码，通过学习源码让我受益匪浅，最近在复现该论文的实验中，我遇到了一些问题，想向您请教。首先您提供的数据训练集与验证集的数量与论文所说的不一样。您提供的数据集中训练集为14664张，验证集为3667张，论文中为14665和3666张。其次我按照论文设置的实验参数，batch64，epoch400，img_size256等参数进行训练，并没有得到论文中的精度。在实验中，我发现400epoch并没有训练收敛，精度还有提升的空间。因为有训练收敛早停止策略，我将epoch设置为一个非常大的值2000，结果得到的经过相差很多，其中map50为0.81，map50-95为0.498
![2](https://github.com/user-attachments/assets/34bcbfbb-61c8-4397-b8fb-29a630feb227)

我以为是我训练图片设置相反了，反过来又重新训练一遍，依然没有得到论文中的精度，其中map50为0.872，map50-95为0.512
![1](https://github.com/user-attachments/assets/a996ea95-a9b9-4487-b6eb-cfdcd830a6e1)
通过仔细阅读源码，我发现map50为0.81是由rgb蒸馏到sar的结果，map50为0.872，是sar蒸馏到rgb的结果。
其中我训练sar当学生的配置文件如下
# Train/val/test sets as 1) dir: path/to/imgs, 2) file: path/to/imgs.txt, or 3) list: [path/to/imgs1, path/to/imgs2, ..]
path: E:\\mhj\\code\\CoLD\\CoLD\\OGSOD-1.0\\  # dataset root dir
train: sar\\images\\train  # train images (relative to 'path')  6471 images
val: sar\\images\\test  # val images (relative to 'path')  548 images
test: sar\\images\\test # test images (optional)  1610 images

train1: E:\\mhj\\code\\CoLD\\CoLD\\OGSOD-1.0\\rgb\\images\\train  # train images (relative to 'path')  6471 images
val1: E:\\mhj\\code\\CoLD\\CoLD\\OGSOD-1.0\\rgb\\images\\test  # val images (relative to 'path')  548 images
test1: E:\\mhj\\code\\\\CoLD\\CoLD\\OGSOD-1.0\\rgb\\images\\test  # test images (optional)  1610 images

# Classes
nc: 3 # number of classes
names: ['bridge', 'harbor', 'storage_tank']

**Comment by mmic-lcl** [comment]
您好，首先非常感谢您对我们工作的关注！关于您提出的一些问题：
1. “所提供的数据训练集与验证集的数量与论文所说的不一样”，该问题原因是由于数据集打包过程中导致，测试集中“912_1_0__0”被错误放在训练集，现已重新打包，正在更新。
2. “按照论文设置的实验参数，并没有得到论文中的精度”，该问题我们重新验证了论文中的数据和参数，所得到的精度与论文所述几乎一致，可能导致细微精度差异的影响因素有安装的环境，设备GPU配置。但值得一提的是，论文对比实验里本文方法采用的是yolov5的X模型，上传的代码默认配置的是s模型，模型的参数量会导致方法的精度差异很大。
3. “发现400epoch并没有训练收敛，精度还有提升的空间”，论文对比实验按照400epoch来训练的，和其他的同质网络对比方法也是公平对比的，在我们后续的一些工作中也对该网络的训练周期进行了调整，发现400epoch以后精度会有一些微弱的提升。
最新代码链接: https://pan.baidu.com/s/19yJKTmcS3Neww5bMjw69ew?pwd=1111 提取码: 1111

**Comment by ciqian6** [comment]
非常感谢您的解答，祝您及全体课题组科研顺利，生活愉快！

**Comment by ciqian6** [comment]
你好，我将单模态的代码中教师模态对学生模态的蒸馏去掉后，发现学生模型的精度也能达到85的精度，而论文中对比基线yolov5为80.9，请问论文中对比的是yolov5s的模型吗？

**Comment by 1246886181** [comment]
> 你好，我将单模态的代码中教师模态对学生模态的蒸馏去掉后，发现学生模型的精度也能达到85的精度，而论文中对比基线yolov5为80.9，请问论文中对比的是yolov5s的模型吗？

你好，能分享下Category-Oriented Localization Distillation for SAR Object Detection and a Unified Benchmark的源码吗？链接失效了

**Comment by mmic-lcl** [comment]
感谢关注，网盘链接不稳定，已重新上传到github中，链接如下：https://github.com/ruanrui/Optical-Image-Guided-SAR-Image-Object-Detection-and-Dataset
