### ISSUE TITLE
Can you share to google drive or icloud?

### ISSUE THREAD

**Issue by evekeen** [mmic-lcl/Datasets-and-benchmark-code#6]
Could you please upload the LaTOT dataset and model to Google Drive or iCloud? baidu.com is not accessible in the US

You can use this link, for example https://drive.google.com/drive/folders/1WWtput3Utb5hvxs7nBycqTiXbwl_OtB2?usp=sharing

Or this one: https://www.icloud.com/iclouddrive/0ff9FMBqAmk2C9fuk-T1XobHA#ML_Shared

**Comment by mmic-lcl** [comment]
We will upload it as soon as possible.

**Comment by mmic-lcl** [comment]
We have uploaded LaTOT to google drive.
